### ISSUE TITLE
[Bug]: Per-account localstorage cache on dash

### ISSUE THREAD

**Issue by Goncharo** [metriport/metriport#1157]
### Steps to reproduce

On the Dash:
- log into account A
- toggle on Sandbox
- log into account B
- toggle off Sandbox
- log into account A

### What did you expect to happen?

Sandbox mode is still toggled on account A.

### What is actually happening?

Sandbox mode has been toggled off for account A based on actions taken on account B.

### Environment

```shell
all
```

### Any additional comments?

Need to think about how to manage cached preferences across accounts, so that one login doesn't affect the other.

**Comment by leite08** [comment]
@Orta21 Is this done?

We just noticed an issue with the banner showing up on the Medical section of the dash regardless of whether the sandbox toggle is on or not, not sure if this was intentional - [context](https://metriport.slack.com/archives/C0616FCPAKZ/p1701365948587689?thread_ts=1701364618.130579&cid=C0616FCPAKZ)

![image](https://github.com/metriport/metriport/assets/2132564/dd3fa75c-f00f-4be5-861b-2d6cae8747a9)

**Comment by Goncharo** [comment]
from @Orta21 - "i fixed that last week"
